### ISSUE TITLE
Add plugin to bower

### ISSUE THREAD

**Issue by orofarne** [makinacorpus/Leaflet.RestoreView#3]
Please, add your plugin to [bower](http://bower.io/).

**Comment by leplatrem** [comment]
Bower can't manage github repos directly ?
/cc @ebrehault @fredericbonifas

**Comment by fredericbonifas** [comment]
Looks like you can use a github repo in your bower.json directly: http://stackoverflow.com/questions/20196707/can-i-add-a-git-repository-to-my-bower-json
