### ISSUE TITLE
Uncaught SecurityError when cookie settings block localStorage

### ISSUE THREAD

**Issue by nrenner** [makinacorpus/Leaflet.RestoreView#5]
Chrome throws a SecurityError when accessing ``window.localStorage`` with [cookie settings](https://support.google.com/chrome/answer/95647?hl=en&co=GENIE.Platform=Desktop) set to *"Block sites from setting any data"*:
``Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`` in ``leaflet.restoreview.js:3``

The Pale Moon browser (and probably older Firefox) is also throwing a SecurityError with restrictive cookie settings.

See also:
* [MDN: Using the Web Storage API - Testing for support vs availability](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#Testing_for_support_vs_availability)
* [Modernizr localstorage.js](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js) feature detect

**Comment by enguerran** [comment]
Thanks for this issue.

I had a verification and a warning message in the console. Maybe we could think to add something more robust to polyfill localStorage if access is not allowed. Or maybe throwing a warning is enough.

@SBats what do you thing?

**Comment by nrenner** [comment]
I think this is fine, wouldn't expect anything else, maybe not even a warning.

Perhaps a comment in the readme that it doesn't work when the Browser settings deny storing local data.

**Comment by SBats** [comment]
@enguerran I like the idea of a warning, simple and efficient in our case. Your pull request does the trick.
@nrenner Thanks for reporting this issue by the way !
