### ISSUE TITLE
Publish plugin on npm registry?

### ISSUE THREAD

**Issue by bagage** [makinacorpus/Leaflet.RestoreView#8]
Would it be possible to publish the plugin on npm registry? Yet we can reference it directly in `package.json` via `"leaflet.restoreview": "https://github.com/makinacorpus/Leaflet.RestoreView",` but this has drawbacks (no reproducibility, no way to know when the plugin changes, *angular cli* not supporting that, not available on CDN like unpkg.com).

It looks like this repo is not having a lot of activity (feature complete and bugs free? :)), but is still a great one!

**Comment by leplatrem** [comment]
@jirimedved could you please add me @leplatrem and @sbats as NPM collaborators?

**Comment by bagage** [comment]
up @leplatrem @jirimedved

**Comment by leplatrem** [comment]
well, if that's an issue (apparently @jirimedved is not active here), you can still submit it yourself as `@bagage/leaflet.restoreview` and use it in your packages deps.

I won't publish it at `@makinacorpus/leaflet.restoreview` because I don't work at Makina Corpus anymore. @gutard maybe?

**Comment by bagage** [comment]
OK thanks @leplatrem, indeed no much activity around here. I've forked the repository and published it to https://www.npmjs.com/package/@bagage/leaflet.restoreview as you advised. Thanks :).
